#! /bin/sh

# _________________________________________________________________________
#
#             Tachyon : A Self-Hosted JavaScript Virtual Machine
#
#
#  This file is part of the Tachyon JavaScript project. Tachyon is
#  distributed at:
#  http://github.com/Tachyon-Team/Tachyon
#
#
#  Copyright (c) 2012, Universite de Montreal
#  All rights reserved.
#
#  This software is licensed under the following license (Modified BSD
#  License):
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are
#  met:
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of the Universite de Montreal nor the names of its
#      contributors may be used to endorse or promote products derived
#      from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
#  IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
#  TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
#  PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL UNIVERSITE DE
#  MONTREAL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
#  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
#  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
#  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
#  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# _________________________________________________________________________


OPT_OUTPUT=""
OPT_PROFILE=""
OPT_HTML=""
OPT_LINENO_WIDTH=""
OPT_PAGE_WIDTH=""
LAST_FILE=""
FILES=""

DIR=`dirname $0`

JSPROFILE="d8 $DIR/../utility/debug.js $DIR/../utility/system.js $DIR/../utility/hashmap.js $DIR/../utility/num.js $DIR/misc.js $DIR/scanner.js $DIR/parser.js $DIR/pp.js $DIR/ast-passes.js $DIR/jsprofile.js --"

while [ "$1" != "" ]; do
  case "$1" in
        "-output") shift
                   OPT_OUTPUT="-output $1" ;;
       "-profile") OPT_PROFILE="-profile" ;;
          "-html") OPT_HTML="-html" ;;
  "-lineno-width") shift
                   OPT_LINENO_WIDTH="-lineno-width $1" ;;
    "-page-width") shift
                   OPT_PAGE_WIDTH="-page-width $1" ;;
             "--") shift
                   break ;;
             *.js) LAST_FILE="$1"
                   FILES="$FILES $LAST_FILE"
                   ;;
                *) echo "Usage: $0 [-output file] [-lineno-width N] [-page-width N] file1.js file2.js ..."
                   exit 1
                   ;;
  esac
  shift
done

if [ "$OPT_OUTPUT" == "" ]; then
  if [ "$OPT_PROFILE" == "" ]; then
    OPT_OUTPUT="-output $LAST_FILE.html"
  else
    OPT_OUTPUT="-output $LAST_FILE.profile"
  fi
fi

$JSPROFILE $OPT_OUTPUT $OPT_PROFILE $OPT_HTML $OPT_LINENO_WIDTH $OPT_PAGE_WIDTH $FILES
